engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
      - faca6a53a5a4ae580279527e261dd1da
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- test/**/*
- static/js/jquery.marquee.min.js
