engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- test/
