osx_image: xcode7.3
sudo: required
dist: trusty

language: c

git:
  depth: 3

branches:
  only:
    - master
    - dev

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx
      env:
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
        - NODE_VERSION=6.3.0
        - BUILD_OS_NAME=darwin
      compiler: clang

before_script:
 - chmod +x ./app/script/travis-build.sh
 - chmod +x ./app/script/build_ml.sh
 - export NODE_VERSION=6.3.0
 - export TEST_RUN=true

script: ./app/script/travis-build.sh

after_success:
  - node_modules/.bin/gulp coverage
  - npm run coveralls
  - npm run codeclimate
  - ./app/script/build_ml.sh

cache:
  apt: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - xvfb
