language: node_js
node_js:
  - '6.1.0'

git:
  depth: 3

branches:
  only:
    - master
    - dev

# env:
#   - NODE_VERSION='5.8.0'

matrix:
  include:
    - os: osx
      env:
        - NODE_VERSION=6.1.0
        - BUILD_OS_NAME=darwin

before_script:
 - chmod +x ./script/travis-build.sh
 - export NODE_VERSION=5.8.0
 - export TEST_RUN=true

script:
  - ./script/travis-build.sh

after_success:
  - node_modules/.bin/gulp coverage
  - npm run coveralls
  - npm run codeclimate

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
