branches:
  only:
    - master
    - dev

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
      dist: trusty
      sudo: required
      language: node_js
      node_js:
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: node_js
      node_js:

before_script:
 - chmod +x ./script/*.sh
 - export NODE_VERSION=$(cat .nvmrc)
 - export TEST_RUN=true

script: ./script/travis-build.sh

after_success:
  # Cleanup
  - rm -rf node_modules coverage .nyc_output
  # Check if build triggered ([build] in commit message)
  - lgcm=$(git log -1 --pretty=%B | xargs echo);
    if [[ $lgcm == *"[build]"* ]]; then
      ./script/build_ml.sh;
    fi

cache:
  apt: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - xvfb
