version: 2.0.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - set NODE_ENV=production
  - ps: Install-Product node 6.3.0 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@next -g # force install next version to test electron-builder
  - npm install --production
  - npm prune

build_script:
  - node --version
  - npm --version
  - build -w --x64

test: off
